### ISSUE TITLE
请问一下“图文互搜.exe”这个工具是怎么做的呀？

### ISSUE THREAD

**Issue by Duanxiaodai** [EternallyTruth/Cross-modal-retrieval#1]
请问一下“图文互搜.exe”这个工具是怎么做的呀？可以分享一下代码么，谢谢

**Comment by Fly2flies** [comment]
我也是第一次把深度模型嵌入到图像检索程序里，
由于时间关系，做的也不是很好！
用的PyQt写的界面，然后稍微写一点点后端的调用就行！
你可以看看GitHub里面其他做的深度学习Web程序学习一下！

**Comment by EternallyTruth** [comment]
I upload the simple UI. You can check it!
[https://github.com/EternallyTruth/Cross-modal-retrieval/blob/master/median_compute/QueryApp/DATA/ImageUI.py](url)

**Comment by EternallyTruth** [comment]
I find a simple UI code and upload it. You can check it!
[](https://github.com/EternallyTruth/Cross-modal-retrieval/blob/master/median_compute/QueryApp/DATA/ImageUI.py)

**Comment by Fly2flies** [comment]
I find a  simple UI code, and you can check it. [https://github.com/EternallyTruth/Cross-modal-retrieval/blob/master/median_compute/QueryApp/DATA/ImageUI.py]()

**Comment by Duanxiaodai** [comment]
哦哦，好的，谢谢

**Comment by Duanxiaodai** [comment]
from QueryApp.MyButton import SwitchButton
from QueryApp.MyLabel import MyLabel
麻烦这个两个包可以分享一下嘛

**Comment by Duanxiaodai** [comment]
from QueryApp.MyButton import SwitchButton
from QueryApp.MyLabel import MyLabel
麻烦这个两个包可以分享一下嘛

**Comment by Duanxiaodai** [comment]
你好，可以分享一下 文件中导入的库包么?
from QueryApp.MyButton import SwitchButton
from QueryApp.MyLabel import MyLabel感谢！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fly2fly"<notifications@github.com&gt;; 
发送时间: 2020年9月15日(星期二) 下午3:48
收件人: "EternallyTruth/Cross-modal-retrieval"<Cross-modal-retrieval@noreply.github.com&gt;; 
抄送: "805236403"<805236403@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [EternallyTruth/Cross-modal-retrieval] 请问一下“图文互搜.exe”这个工具是怎么做的呀？ (#1)





 
I find a  simple UI code, and you can check it. https://github.com/EternallyTruth/Cross-modal-retrieval/blob/master/median_compute/QueryApp/DATA/ImageUI.py

**Comment by LrnRuiZ** [comment]
您好，后端调用的内容是不是没有share呀，如果可以的话可以分享一下供学习一下吗？万分感谢！
